var customDict = {
    'attachment':'অ্যাটাচমেন্ট',
    'tutorial': 'টিউটোরিয়াল',
    'approve':'অ্যাপ্রুভ',
    'admin':'অ্যাডমিন',
    'administration':'অ্যাডমিনিস্ট্রেশন',
    'adminta':'অ্যাডমিনটা',
    'approach':'অ্যাপ্রোচ',
    'approve':'অ্যাপ্রুভ',
    'backend':'ব্যাকএন্ড',
    'challenge':'চ্যালেঞ্জ',
    'disk':'ডিস্ক',
    'frontend':'ফ্রন্টএন্ড',
    'function':'ফাংশন',
    'golang':'গো-ল্যাং',
    'javascript':'জাভাস্ক্রিপ্ট',
    'js':'জেএস',
    'node':'নোড',
    'online':'অনলাইন',
    'package':'প্যাকেজ',
    'startup':'স্টার্টআপ',
    'variable':'ভ্যারিয়েবল'
};
